name: Setup S3FS
description: Sets up and configures rexray S3FS docker plugin
inputs:
  s3fs-access-key:
    description: 'AWS access key'
  s3fs-secret-key:
    description: 'AWS secret key'
continue-on-error: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        docker plugin install franciscoda/s3fs AWSACCESSKEYID=${{inputs.s3fs-access-key}} AWSSECRETACCESSKEY=${{inputs.s3fs-secret-key}} --grant-all-permissions
